# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#000000"
foreground = "#C1C1C1"

[colors.normal]
black   = "#000000"
red     = "#5F8787"
green   = "#D0DFEE"
yellow  = "#5F81A5"
blue    = "#888888"
magenta = "#999999"
cyan    = "#AAAAAA"
white   = "#C1C1C1"

[colors.bright]
black   = "#333333"
red     = "#5F8787"
green   = "#D0DFEE"
yellow  = "#5F81A5"
blue    = "#888888"
magenta = "#999999"
cyan    = "#AAAAAA"
white   = "#C1C1C1"
